name: Terraform & Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: # Required for OIDC authentication
      id-token: write  # Required for OIDC authentication
      contents: read   # Required to checkout the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.arn_github_actions_role }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.TF_VAR_region }}

      - name: Generate backend.tf Dynamically
        run: |
          cat <<EOF > infrastructure/backend.tf
          terraform {
            backend "s3" {
              bucket         = "${{ secrets.TF_STATE_BACKEND_BUCKET_NAME }}"
              key            = "terraform_state/statefile.tfstate"
              region         = "${{ secrets.TF_VAR_REGION }}"
              encrypt        = true
              dynamodb_table = "${{ secrets.TF_STATE_LOCK_TABLE }}"
            }
          }
          EOF

          echo "Generated infrastructure/backend.tf:"
          cat infrastructure/backend.tf  # Debugging step

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: List files for debugging
        run: ls -R infrastructure  # Debugging step

      - name: Initialize Terraform
        run: terraform init
        working-directory: infrastructure

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: infrastructure

      - name: Set Terraform Variables
        run: |
          echo "TF_VAR_allowed_ssh_ip=${{ secrets.TF_VAR_ALLOWED_SSH_IP }}" >> $GITHUB_ENV
          echo "TF_VAR_key_name=${{ secrets.TF_VAR_SSH_KEY_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_db_user=${{ secrets.TF_VAR_DB_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_db_name=${{ secrets.TF_VAR_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ secrets.TF_VAR_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${{ secrets.TF_VAR_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Debug Terraform Variables
        run: env | grep TF_VAR_  # Ensure all Terraform variables are set

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure
